from .term_disc import termDiscount
from .term_trace_hess import termTraceHessian
from .term_convection import termConvection
from .term_curvature import termCurvature
from .term_forcing import termForcing
from .term_lax_friedrich import termLaxFriedrichs
from .term_normal import termNormal
from .term_sum import termSum
from .term_reinit import termReinit
from .term_restrict_update import termRestrictUpdate
